apply plugin: 'com.android.application'

android {
  namespace = "me.drakeet.toast.sample"
  compileSdk gradle.compileSdkVersion

  defaultConfig {
    applicationId "me.drakeet.toast.sample"
    minSdk gradle.minSdkVersion
    targetSdk gradle.targetSdkVersion
    versionCode gradle.versionCode
    versionName gradle.versionName
    testInstrumentationRunner 'androidx.test.runner.AndroidJUnitRunner'
  }

  buildTypes {
    release {
      minifyEnabled false
      proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
    }
  }

  compileOptions {
    sourceCompatibility JavaVersion.VERSION_17
    targetCompatibility JavaVersion.VERSION_17
  }
}


dependencies {
  implementation project(':library')
  implementation fileTree(dir: 'libs', include: ['*.jar'])
  implementation 'androidx.appcompat:appcompat:1.7.0'
  // testImplementation 'junit:junit:4.12'
  // androidTestImplementation 'com.android.support.test:runner:1.0.2'
  // androidTestImplementation 'com.android.support.test:rules:1.0.2'
  // androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'
}

